### ISSUE TITLE
wrong instruments played

### ISSUE THREAD

**Issue by ProfessorSniff** [SemmieDev/Disc-Jockey#1]
a note sequence of 
`harp, bass, bass drum, snare, click, guitar, flute, bell, chime, xylophone, iron xylophone, cowbell, digeridoo, bit, banjo, pling`
is played as
`harp, bass drum, snare, click, bass, flute, bell, guitar, chime, xylophone, iron xylophone, cowbell, digeridoo, bit, banjo, pling`

from other testing, it looks like the instruments are swapped, rather than the note order.
if a video and/or the nbs file would be helpful, those can be provided.

**Comment by SemmieDev** [comment]
Yea please give the NBS file so I can look into it

**Comment by ProfessorSniff** [comment]
![image](https://user-images.githubusercontent.com/65641177/156902691-653e2a03-4bb5-4131-8ba9-f2bd0214d509.png)
[test1.nbs.zip](https://github.com/SemmieboyYT/Disc-Jockey/files/8191640/test1.nbs.zip)

a video of the file being played:
https://user-images.githubusercontent.com/65641177/156902660-379e28d3-164c-4eee-a563-9d8d47d55c86.mp4

the note pitches are played in the correct order as shown by vanillatweaks' note block texture pack, but some instruments are switched.

**Comment by SemmieDev** [comment]
Fixed in 1.0.1, thanks for reporting the issue.
