### ISSUE TITLE
No tutorial

### ISSUE THREAD

**Issue by ghost** [SemmieDev/Disc-Jockey#2]
When I try to construct the build of noteblocks it says I need more materials when I have placed down all of them within my reach and I cannot build all of them Infront of me within my reach and vie
![2022-03-07_10 11 01](https://user-images.githubusercontent.com/101104185/157011586-1bd4c409-d757-4cdd-88f1-9109c990a581.png)
![2022-03-07_10 11 12](https://user-images.githubusercontent.com/101104185/157011598-1eef23fa-78e6-4d90-8dad-2bf4a5732eef.png)
w

**Comment by SemmieDev** [comment]
You have more reach in creative mode, check again in survival mode
