### ISSUE TITLE
Please update to 1.21

### ISSUE THREAD

**Issue by NDSSTUDIO** [SemmieDev/Disc-Jockey#27]
We need this mod to play music on the server. Thank you! XD

**Comment by SemmieDev** [comment]
This is a purely client side mod, and it is staying that way. Using [Open Note Block Studio](https://opennbs.org/) you can export a song to a datapack, you should try that instead.

**Comment by NDSSTUDIO** [comment]
> This is a purely client side mod, and it is staying that way. Using [Open Note Block Studio](https://opennbs.org/) you can export a song to a datapack, you should try that instead.



It seems that the translation is not very accurate. I think what I meant is to play music for friends on the server. However, I currently use ViaFabric to solve this small problem. Of course, 1.21 will be more convenient. XD
