### ISSUE TITLE
i can't see songs

### ISSUE THREAD

**Issue by vi945786** [SemmieDev/Disc-Jockey#3]
i can't see any songs even after doing /discjockey reload

**Comment by SemmieDev** [comment]
By default it doesn't contain any songs. Try searching for "minecraft nbs files" or something like that. You can also always make your own songs.

**Comment by TheOneAndOnlyDanSan** [comment]
i put it in the right folder

**Comment by SemmieDev** [comment]
Song should be placed in ".minecraft/config/disc_jockey/songs" and shouldn't be in a archive (.zip, .rar). If it still doesn't work, please send me the logs located at ".minecraft/logs/latest.log".
