### ISSUE TITLE
The note block at the edge of the touch range will not be judged.

### ISSUE THREAD

**Issue by x-yingcan-x** [SemmieDev/Disc-Jockey#4]
If a note block needs you to aim well to reach it, in other words, if it is on the edge of your touch range, it won't be judged. I'm sure I switched to survival mode, and I can actually touch it.
I'm so sorry.I used mechanical translation and may have uploaded it twice.

**Comment by x-yingcan-x** [comment]
I forgot that this problem is very similar to #2. It may not be very important to fix it, just to put down more note blocks

**Comment by SemmieDev** [comment]
This is because its calculating the distance to the middle of the note blocks. Its not super easy to fix this, but I will try.

**Comment by SemmieDev** [comment]
Fixed in v1.2.0
